"""Unit tests for ``onvif_compare.pcap``.

Uses synthetic PCAP fixtures generated by ``tests/fixtures/make_pcaps.py``.
No network access.  No tshark.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from onvif_compare.models import EventSource, SoapOperation
from onvif_compare.pcap import (
    HttpTransaction,
    _decode_chunked,
    _extract_body,
    _http_status,
    _is_soap,
    _split_http_messages,
    extract_transactions,
    reconstruct_streams,
)

FIXTURES = Path(__file__).parent / "fixtures" / "pcap"
CAMERA_IP = "192.168.1.100"
PROTECT_IP = "10.54.4.1"


def _good_pcap() -> str:
    return str(FIXTURES / "capture_good.pcap")


def _fault_pcap() -> str:
    return str(FIXTURES / "capture_fault.pcap")


# ---------------------------------------------------------------------------
# HTTP helpers
# ---------------------------------------------------------------------------


class TestHttpHelpers:
    def test_is_soap_true(self):
        assert _is_soap(b"<s:Envelope xmlns:s='...'><s:Body/></s:Envelope>")

    def test_is_soap_false(self):
        assert not _is_soap(b"<html><body>hello</body></html>")

    def test_is_soap_empty(self):
        assert not _is_soap(b"")

    def test_http_status_200(self):
        hdrs = b"HTTP/1.1 200 OK\r\nContent-Type: text/xml\r\n"
        assert _http_status(hdrs) == 200

    def test_http_status_500(self):
        hdrs = b"HTTP/1.1 500 Internal Server Error\r\n"
        assert _http_status(hdrs) == 500

    def test_http_status_malformed(self):
        assert _http_status(b"GARBAGE") == 0

    def test_decode_chunked(self):
        chunked = b"5\r\nhello\r\n6\r\n world\r\n0\r\n\r\n"
        assert _decode_chunked(chunked) == b"hello world"

    def test_decode_chunked_empty(self):
        assert _decode_chunked(b"0\r\n\r\n") == b""

    def test_split_http_messages_single(self):
        raw = b"POST / HTTP/1.1\r\nContent-Length: 5\r\n\r\nhello"
        msgs = _split_http_messages(raw)
        assert len(msgs) == 1
        assert msgs[0][1] == b"hello"

    def test_split_http_messages_no_separator(self):
        # No \r\n\r\n — returns empty list
        assert _split_http_messages(b"garbage") == []


# ---------------------------------------------------------------------------
# Good PCAP — PullMessages with IsMotion=true
# ---------------------------------------------------------------------------


class TestGoodPcap:
    def setup_method(self):
        self.transactions = reconstruct_streams(
            _good_pcap(),
            camera_ip=CAMERA_IP,
            protect_ip=PROTECT_IP,
        )

    def test_at_least_one_transaction(self):
        assert len(self.transactions) >= 1

    def test_transaction_type(self):
        assert isinstance(self.transactions[0], HttpTransaction)

    def test_src_dst_ips(self):
        txn = self.transactions[0]
        assert PROTECT_IP in (txn.src_ip, txn.dst_ip)
        assert CAMERA_IP in (txn.src_ip, txn.dst_ip)

    def test_http_status_200(self):
        assert self.transactions[0].http_status == 200

    def test_response_body_is_soap(self):
        assert _is_soap(self.transactions[0].response_body)

    def test_extract_transactions_returns_pull_transaction(self):
        pull_txns, faults = extract_transactions(
            self.transactions,
            camera_ip=CAMERA_IP,
            protect_ip=PROTECT_IP,
        )
        assert len(pull_txns) >= 1
        assert faults == []

    def test_notification_extracted(self):
        pull_txns, _ = extract_transactions(
            self.transactions,
            camera_ip=CAMERA_IP,
            protect_ip=PROTECT_IP,
        )
        assert any(len(t.notifications) > 0 for t in pull_txns)

    def test_is_motion_true(self):
        pull_txns, _ = extract_transactions(
            self.transactions,
            camera_ip=CAMERA_IP,
            protect_ip=PROTECT_IP,
        )
        events = [n for t in pull_txns for n in t.notifications]
        assert any(e.is_motion is True for e in events)

    def test_source_is_protect(self):
        pull_txns, _ = extract_transactions(
            self.transactions,
            camera_ip=CAMERA_IP,
            protect_ip=PROTECT_IP,
        )
        assert all(t.source == EventSource.PROTECT for t in pull_txns)

    def test_provenance_fields(self):
        pull_txns, _ = extract_transactions(
            self.transactions,
            camera_ip=CAMERA_IP,
            protect_ip=PROTECT_IP,
        )
        txn = pull_txns[0]
        assert txn.tcp_stream >= 0
        assert txn.request_frame > 0
        assert txn.response_frame > 0

    def test_raw_bodies_retained(self):
        pull_txns, _ = extract_transactions(
            self.transactions,
            camera_ip=CAMERA_IP,
            protect_ip=PROTECT_IP,
        )
        txn = pull_txns[0]
        assert len(txn.raw_response) > 0


# ---------------------------------------------------------------------------
# Fault PCAP — PullMessages returning SOAP fault
# ---------------------------------------------------------------------------


class TestFaultPcap:
    def setup_method(self):
        self.transactions = reconstruct_streams(
            _fault_pcap(),
            camera_ip=CAMERA_IP,
            protect_ip=PROTECT_IP,
        )

    def test_at_least_one_transaction(self):
        assert len(self.transactions) >= 1

    def test_http_status_500(self):
        assert self.transactions[0].http_status == 500

    def test_fault_extracted(self):
        _, faults = extract_transactions(
            self.transactions,
            camera_ip=CAMERA_IP,
            protect_ip=PROTECT_IP,
        )
        assert len(faults) >= 1

    def test_fault_code(self):
        _, faults = extract_transactions(
            self.transactions,
            camera_ip=CAMERA_IP,
            protect_ip=PROTECT_IP,
        )
        assert "Receiver" in faults[0].code

    def test_fault_subcode(self):
        _, faults = extract_transactions(
            self.transactions,
            camera_ip=CAMERA_IP,
            protect_ip=PROTECT_IP,
        )
        assert faults[0].subcode is not None

    def test_pull_transaction_has_fault(self):
        pull_txns, _ = extract_transactions(
            self.transactions,
            camera_ip=CAMERA_IP,
            protect_ip=PROTECT_IP,
        )
        assert any(t.soap_fault is not None for t in pull_txns)
